### PR TITLE
created Fortran solution to FizzBuzz

### PR DESCRIPTION
**Pull request by elijahblake12**
I created a fortran file to solve FizzBuzz, a shell script to take user input for n, and a readme for instructions on running the fortran program.

### CODE REVIEW

**Review by RansomBowman — COMMENTED** [review]
Review below shows that I have the branch checked out and how I got the code running:

Looks good code wise, except a.out doesn't work on windows. Changing a.out to a.exe in 'run.sh' resolved the issue and the program ran correctly. Also, creating the a.exe file freaks windows security out.
Working output of code:
Coderunafteraexechange
Code when a.out is in  run.sh instead of a.exe:
aoutFailure
a.out in run.sh:
aout
a.exe in run.sh:
aexe

**Comment by elijahblake12** [comment]
Hey Ransom, thanks for bringing this issue to my attention, I specified the output filename; it should work on all systems now. Can you pull it down and give it another run? Thanks!

**Comment by akattine** [comment]
Looks good! +1

**Review by RansomBowman — APPROVED** [review]
Code works and problems resolved. +1 and +10

**Pull request merged**
