### PR TITLE
Fizzbuzz/anthonynardielloc#

### PR DESCRIPTION
**Pull request by nardielloam7451**
Adds the C# fizzbuzz solution

### CODE REVIEW

**Review by isabellejoy00 — APPROVED** [review]
Looks good! +1

**Comment by isabellejoy00** [comment]
Hey Anthony,
I downloaded the SDK and tried running the shell script but I got this error message and I'm not sure what's causing it.
Screen Shot 2021-03-02 at 9 40 46 PM

**Comment by nardielloam7451** [comment]
> Hey Anthony,
> I downloaded the SDK and tried running the shell script but I got this error message and I'm not sure what's causing it.
> Screen Shot 2021-03-02 at 9 40 46 PM

Hmm, interesting!! Let me take a look, but I think I just need to fix one command in the Script!!

**Comment by sleddog** [comment]
@nardielloam7451 seems like you can merge this now...

**Pull request merged**
